import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

export default function Login() {
  const { login, verifyMFA } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  // MFA Challenge State
  const [mfaChallenge, setMfaChallenge] = useState(null); // { mfaTicket, email, mfaType }
  const [totpCode, setTotpCode] = useState('');

  async function handleSubmit(e) {
    e.preventDefault();
    setError('');
    setLoading(true);
    try {
      const res = await login(email, password);
      if (res && res.mfaRequired) {
        setMfaChallenge({
          mfaTicket: res.mfaTicket,
          email: res.email,
          mfaType: res.mfaType || 'totp'
        });
        setTotpCode('');
        return;
      }
      navigate('/');
    } catch (err) {
      setError(err.response?.data?.error || err.message || 'Authentication failed. Please verify credentials.');
    } finally {
      setLoading(false);
    }
  }

  async function handleMfaSubmit(e) {
    e.preventDefault();
    if (!totpCode || totpCode.trim().length !== 6) {
      setError('Please enter a valid 6-digit authenticator code.');
      return;
    }
    setError('');
    setLoading(true);
    try {
      await verifyMFA(mfaChallenge.mfaTicket, totpCode.trim());
      navigate('/');
    } catch (err) {
      setError(err.response?.data?.error || err.message || 'Invalid or expired authenticator code.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="auth-split-container">
      {/* Visual Cyberpunk Banner Side */}
      <div className="auth-visual-side">
        <h1 className="auth-visual-title">CYBER SENTINEL</h1>
        <p className="auth-visual-text">
          Advanced Threat Intelligence &amp; Neural Network Security Operations Command Center. Continuous system diagnostics and WAF mitigation sandboxing.
        </p>
      </div>

      {/* Login Credentials / MFA Challenge Form Side */}
      <div className="auth-form-side">
        <div className="auth-card">
          <div className="brand auth-brand">
            <span className="brand-mark">
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="var(--accent-cyan)" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ filter: 'drop-shadow(0 0 8px var(--accent-cyan-dim))' }}>
                <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>
              </svg>
            </span>
            <span className="brand-name" style={{ fontSize: '20px', letterSpacing: '0.05em', textShadow: '0 0 8px var(--accent-cyan-dim)' }}>
              {mfaChallenge ? 'MFA VERIFICATION' : 'COMMAND GATEWAY'}
            </span>
          </div>

          <p className="auth-subtitle" style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '20px' }}>
            {mfaChallenge ? 'Time-Based One-Time Password (TOTP)' : 'Operator Authentication & Access Control'}
          </p>

          {/* Render MFA Challenge View if Required */}
          {mfaChallenge ? (
            <form onSubmit={handleMfaSubmit} className="auth-form">
              <div style={{
                padding: '14px',
                background: 'rgba(0, 212, 255, 0.08)',
                border: '1px solid rgba(0, 212, 255, 0.25)',
                borderRadius: '8px',
                marginBottom: '16px',
                fontSize: '12px',
                color: 'var(--text-dim)',
                lineHeight: 1.5
              }}>
                <div style={{ color: 'var(--accent-cyan)', fontWeight: 700, marginBottom: '4px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                  <span>🛡️</span> AUTHENTICATOR APP REQUIRED
                </div>
                Enter the 6-digit security code generated by <strong>Google Authenticator</strong>, <strong>Microsoft Authenticator</strong>, or <strong>Authy</strong>.
                <div style={{ marginTop: '8px', fontSize: '11px', color: 'var(--text-faint)' }}>
                  Target: <code>{mfaChallenge.email}</code>
                </div>
              </div>

              <label>
                AUTHENTICATOR 6-DIGIT CODE
                <input 
                  type="text" 
                  maxLength={6}
                  value={totpCode} 
                  onChange={(e) => setTotpCode(e.target.value.replace(/\D/g, ''))} 
                  required 
                  placeholder="000000" 
                  autoComplete="one-time-code"
                  autoFocus
                  style={{
                    fontSize: '20px',
                    letterSpacing: '0.25em',
                    textAlign: 'center',
                    fontFamily: 'JetBrains Mono, monospace',
                    fontWeight: 800,
                    color: 'var(--accent-cyan)',
                    marginTop: '6px'
                  }}
                />
              </label>

              {error && (
                <div 
                  className="form-error"
                  style={{
                    padding: '10px 14px',
                    background: 'rgba(255, 68, 68, 0.15)',
                    border: '1px solid rgba(255, 68, 68, 0.4)',
                    borderRadius: '6px',
                    color: '#ff6b6b',
                    fontSize: '12px',
                    marginBottom: '12px'
                  }}
                >
                  {error}
                </div>
              )}

              <button 
                type="submit" 
                className="btn-primary" 
                disabled={loading} 
                style={{ padding: '12px', fontSize: '14px', fontWeight: '700', letterSpacing: '0.05em', marginTop: '8px' }}
              >
                {loading ? 'VERIFYING CODE...' : 'CONFIRM MFA CODE'}
              </button>

              <button
                type="button"
                onClick={() => { setMfaChallenge(null); setError(''); }}
                style={{
                  width: '100%',
                  marginTop: '12px',
                  background: 'transparent',
                  border: 'none',
                  color: 'var(--text-faint)',
                  fontSize: '12px',
                  cursor: 'pointer',
                  textDecoration: 'underline'
                }}
              >
                ← Back to Password Login
              </button>
            </form>
          ) : (
            /* Standard Password Form (Step 1) */
            <>
              <form onSubmit={handleSubmit} className="auth-form">
                <label>
                  OPERATOR ID (EMAIL)
                  <input 
                    type="email" 
                    value={email} 
                    onChange={(e) => setEmail(e.target.value)} 
                    required 
                    placeholder="analyst@sentinel.local" 
                    autoComplete="email"
                  />
                </label>

                <label>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span>ACCESS PASSCODE</span>
                    <span style={{ fontSize: '10px', color: 'var(--accent-green)', fontFamily: 'Space Grotesk' }}>Secured</span>
                  </div>
                  <div style={{ position: 'relative', marginTop: '6px' }}>
                    <input 
                      type={showPassword ? 'text' : 'password'} 
                      value={password} 
                      onChange={(e) => setPassword(e.target.value)} 
                      required 
                      placeholder="••••••••" 
                      autoComplete="current-password"
                      style={{ paddingRight: '42px', marginTop: 0 }} 
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(p => !p)}
                      style={{
                        position: 'absolute',
                        right: '12px',
                        top: '50%',
                        transform: 'translateY(-50%)',
                        background: 'none',
                        border: 'none',
                        cursor: 'pointer',
                        color: 'var(--text-faint)',
                        fontSize: '14px',
                        padding: 0,
                        lineHeight: 1,
                      }}
                      title={showPassword ? 'Hide password' : 'Show password'}
                    >
                      {showPassword ? '🙈' : '👁️'}
                    </button>
                  </div>
                </label>

                {error && (
                  <div 
                    className="form-error"
                    style={{
                      padding: '10px 14px',
                      background: 'rgba(255, 68, 68, 0.15)',
                      border: '1px solid rgba(255, 68, 68, 0.4)',
                      borderRadius: '6px',
                      color: '#ff6b6b',
                      fontSize: '12px',
                      marginBottom: '12px'
                    }}
                  >
                    {error}
                  </div>
                )}

                <button 
                  type="submit" 
                  className="btn-primary" 
                  disabled={loading} 
                  style={{ padding: '12px', fontSize: '14px', fontWeight: '700', letterSpacing: '0.05em', marginTop: '8px' }}
                >
                  {loading ? 'AUTHENTICATING...' : 'ENTER COMMAND CENTER'}
                </button>
              </form>

              <div style={{ marginTop: '16px', display: 'flex', justifyContent: 'space-between', fontSize: '12px' }}>
                <Link to="/forgot-password" style={{ color: 'var(--text-faint)', textDecoration: 'none' }}>
                  Forgot passcode?
                </Link>
                <Link to="/register" style={{ color: 'var(--accent-cyan)', textDecoration: 'none' }}>
                  Deploy new operator card →
                </Link>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
